# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cinco.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cinco(object):
    def setupUi(self, cinco):
        cinco.setObjectName("cinco")
        cinco.resize(734, 607)
        cinco.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.centralwidget = QtWidgets.QWidget(cinco)
        self.centralwidget.setObjectName("centralwidget")
        self.boton6_3 = QtWidgets.QPushButton(self.centralwidget)
        self.boton6_3.setGeometry(QtCore.QRect(530, 260, 71, 23))
        self.boton6_3.setStyleSheet("background-color: rgb(255, 186, 129);")
        self.boton6_3.setObjectName("boton6_3")
        self.line_18 = QtWidgets.QFrame(self.centralwidget)
        self.line_18.setGeometry(QtCore.QRect(520, 90, 3, 90))
        self.line_18.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_18.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.line_17 = QtWidgets.QFrame(self.centralwidget)
        self.line_17.setGeometry(QtCore.QRect(420, 90, 3, 90))
        self.line_17.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_17.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.boton6_1 = QtWidgets.QPushButton(self.centralwidget)
        self.boton6_1.setGeometry(QtCore.QRect(530, 120, 71, 23))
        self.boton6_1.setStyleSheet("background-color: rgb(255, 186, 129);")
        self.boton6_1.setObjectName("boton6_1")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(130, 290, 70, 3))
        self.line_4.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 60, 71, 20))
        self.label.setObjectName("label")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(330, 180, 70, 3))
        self.line_3.setStyleSheet("background-color: rgb(36, 255, 12);")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(520, 60, 81, 20))
        self.label_9.setObjectName("label_9")
        self.boton5_3 = QtWidgets.QPushButton(self.centralwidget)
        self.boton5_3.setGeometry(QtCore.QRect(430, 260, 71, 23))
        self.boton5_3.setStyleSheet("background-color: rgb(254, 255, 167);")
        self.boton5_3.setObjectName("boton5_3")
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(430, 290, 70, 3))
        self.line_10.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.boton4 = QtWidgets.QPushButton(self.centralwidget)
        self.boton4.setGeometry(QtCore.QRect(330, 90, 71, 23))
        self.boton4.setStyleSheet("background-color: rgb(49, 147, 0);")
        self.boton4.setObjectName("boton4")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(530, 180, 70, 3))
        self.line_9.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(230, 290, 70, 3))
        self.line_5.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(330, 290, 70, 3))
        self.line_6.setStyleSheet("background-color: rgb(36, 255, 12);")
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.boton1_1 = QtWidgets.QPushButton(self.centralwidget)
        self.boton1_1.setGeometry(QtCore.QRect(130, 120, 71, 23))
        self.boton1_1.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.boton1_1.setObjectName("boton1_1")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(130, 180, 70, 3))
        self.line.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.boton2_1 = QtWidgets.QPushButton(self.centralwidget)
        self.boton2_1.setGeometry(QtCore.QRect(130, 220, 470, 23))
        self.boton2_1.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.boton2_1.setObjectName("boton2_1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 60, 21, 20))
        self.label_2.setObjectName("label_2")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(430, 60, 21, 20))
        self.label_8.setObjectName("label_8")
        self.boton1 = QtWidgets.QPushButton(self.centralwidget)
        self.boton1.setGeometry(QtCore.QRect(130, 90, 71, 23))
        self.boton1.setStyleSheet("background-color: rgb(151, 191, 255);")
        self.boton1.setObjectName("boton1")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(330, 60, 21, 20))
        self.label_3.setObjectName("label_3")
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setGeometry(QtCore.QRect(410, 90, 3, 90))
        self.line_11.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.boton4_3 = QtWidgets.QPushButton(self.centralwidget)
        self.boton4_3.setGeometry(QtCore.QRect(330, 260, 71, 23))
        self.boton4_3.setStyleSheet("background-color: rgb(133, 203, 120);")
        self.boton4_3.setObjectName("boton4_3")
        self.boton6 = QtWidgets.QPushButton(self.centralwidget)
        self.boton6.setGeometry(QtCore.QRect(530, 90, 71, 23))
        self.boton6.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.boton6.setObjectName("boton6")
        self.boton1_3 = QtWidgets.QPushButton(self.centralwidget)
        self.boton1_3.setGeometry(QtCore.QRect(130, 260, 71, 23))
        self.boton1_3.setStyleSheet("background-color: rgb(208, 255, 255);")
        self.boton1_3.setObjectName("boton1_3")
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setGeometry(QtCore.QRect(210, 90, 3, 90))
        self.line_12.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.boton5_1 = QtWidgets.QPushButton(self.centralwidget)
        self.boton5_1.setGeometry(QtCore.QRect(430, 120, 71, 23))
        self.boton5_1.setStyleSheet("background-color: rgb(254, 255, 167);")
        self.boton5_1.setObjectName("boton5_1")
        self.boton3_3 = QtWidgets.QPushButton(self.centralwidget)
        self.boton3_3.setGeometry(QtCore.QRect(230, 260, 71, 23))
        self.boton3_3.setStyleSheet("background-color: rgb(255, 197, 187);")
        self.boton3_3.setObjectName("boton3_3")
        self.line_13 = QtWidgets.QFrame(self.centralwidget)
        self.line_13.setGeometry(QtCore.QRect(220, 90, 3, 90))
        self.line_13.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.boton3_2 = QtWidgets.QPushButton(self.centralwidget)
        self.boton3_2.setGeometry(QtCore.QRect(230, 150, 71, 23))
        self.boton3_2.setStyleSheet("background-color: rgb(255, 197, 187);")
        self.boton3_2.setObjectName("boton3_2")
        self.boton1_2 = QtWidgets.QPushButton(self.centralwidget)
        self.boton1_2.setGeometry(QtCore.QRect(130, 150, 71, 23))
        self.boton1_2.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.boton1_2.setObjectName("boton1_2")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(230, 180, 70, 3))
        self.line_2.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_16 = QtWidgets.QFrame(self.centralwidget)
        self.line_16.setGeometry(QtCore.QRect(530, 290, 70, 3))
        self.line_16.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.line_15 = QtWidgets.QFrame(self.centralwidget)
        self.line_15.setGeometry(QtCore.QRect(320, 90, 3, 90))
        self.line_15.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.boton4_1 = QtWidgets.QPushButton(self.centralwidget)
        self.boton4_1.setGeometry(QtCore.QRect(330, 120, 71, 23))
        self.boton4_1.setStyleSheet("background-color: rgb(133, 203, 120);")
        self.boton4_1.setObjectName("boton4_1")
        self.boton3 = QtWidgets.QPushButton(self.centralwidget)
        self.boton3.setGeometry(QtCore.QRect(230, 90, 71, 23))
        self.boton3.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.boton3.setObjectName("boton3")
        self.boton5 = QtWidgets.QPushButton(self.centralwidget)
        self.boton5.setGeometry(QtCore.QRect(430, 90, 71, 23))
        self.boton5.setStyleSheet("background-color: rgb(49, 147, 0);\n"
"background-color: rgb(255, 255, 127);")
        self.boton5.setObjectName("boton5")
        self.resultado = QtWidgets.QTextEdit(self.centralwidget)
        self.resultado.setGeometry(QtCore.QRect(130, 300, 471, 131))
        self.resultado.setStyleSheet("background-color: rgb(234, 234, 234);")
        self.resultado.setObjectName("resultado")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(430, 180, 70, 3))
        self.line_7.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(310, 90, 3, 90))
        self.line_8.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_14 = QtWidgets.QFrame(self.centralwidget)
        self.line_14.setGeometry(QtCore.QRect(510, 90, 3, 90))
        self.line_14.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.boton4_2 = QtWidgets.QPushButton(self.centralwidget)
        self.boton4_2.setGeometry(QtCore.QRect(330, 150, 71, 23))
        self.boton4_2.setStyleSheet("background-color: rgb(133, 203, 120);")
        self.boton4_2.setObjectName("boton4_2")
        self.boton2 = QtWidgets.QPushButton(self.centralwidget)
        self.boton2.setGeometry(QtCore.QRect(130, 190, 470, 23))
        self.boton2.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.boton2.setObjectName("boton2")
        self.boton6_2 = QtWidgets.QPushButton(self.centralwidget)
        self.boton6_2.setGeometry(QtCore.QRect(530, 150, 71, 23))
        self.boton6_2.setStyleSheet("background-color: rgb(255, 186, 129);")
        self.boton6_2.setObjectName("boton6_2")
        self.boton5_2 = QtWidgets.QPushButton(self.centralwidget)
        self.boton5_2.setGeometry(QtCore.QRect(430, 150, 71, 23))
        self.boton5_2.setStyleSheet("background-color: rgb(254, 255, 167);")
        self.boton5_2.setObjectName("boton5_2")
        self.boton3_1 = QtWidgets.QPushButton(self.centralwidget)
        self.boton3_1.setGeometry(QtCore.QRect(230, 120, 71, 23))
        self.boton3_1.setStyleSheet("background-color: rgb(255, 197, 187);")
        self.boton3_1.setObjectName("boton3_1")
        self.line_19 = QtWidgets.QFrame(self.centralwidget)
        self.line_19.setGeometry(QtCore.QRect(340, 490, 70, 3))
        self.line_19.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.boton6_4 = QtWidgets.QPushButton(self.centralwidget)
        self.boton6_4.setGeometry(QtCore.QRect(340, 460, 71, 23))
        self.boton6_4.setStyleSheet("background-color: rgb(255, 186, 129);")
        self.boton6_4.setObjectName("boton6_4")
        cinco.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(cinco)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 734, 21))
        self.menubar.setObjectName("menubar")
        cinco.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(cinco)
        self.statusbar.setObjectName("statusbar")
        cinco.setStatusBar(self.statusbar)

        self.retranslateUi(cinco)
        QtCore.QMetaObject.connectSlotsByName(cinco)

    def retranslateUi(self, cinco):
        _translate = QtCore.QCoreApplication.translate
        cinco.setWindowTitle(_translate("cinco", "MainWindow"))
        self.boton6_3.setText(_translate("cinco", "Reiniciar CSVs"))
        self.boton6_1.setText(_translate("cinco", "Graficar"))
        self.label.setText(_translate("cinco", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Condición 1</span></p></body></html>"))
        self.label_9.setText(_translate("cinco", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Condición 5</span></p></body></html>"))
        self.boton5_3.setText(_translate("cinco", "Reiniciar CSVs"))
        self.boton4.setText(_translate("cinco", "Importar CSV"))
        self.boton1_1.setText(_translate("cinco", "Graficar "))
        self.boton2_1.setText(_translate("cinco", "Graficar meanPSD y PA CH2"))
        self.label_2.setText(_translate("cinco", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">C2</span></p></body></html>"))
        self.label_8.setText(_translate("cinco", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">C4</span></p></body></html>"))
        self.boton1.setText(_translate("cinco", "Importar CSV"))
        self.label_3.setText(_translate("cinco", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">C3</span></p></body></html>"))
        self.boton4_3.setText(_translate("cinco", "Reiniciar CSVs"))
        self.boton6.setText(_translate("cinco", "Importar CSV"))
        self.boton1_3.setText(_translate("cinco", "Reiniciar CSVs"))
        self.boton5_1.setText(_translate("cinco", "Graficar"))
        self.boton3_3.setText(_translate("cinco", "Reiniciar CSVs"))
        self.boton3_2.setText(_translate("cinco", "meanPSD"))
        self.boton1_2.setText(_translate("cinco", "meanPSD "))
        self.boton4_1.setText(_translate("cinco", "Graficar"))
        self.boton3.setText(_translate("cinco", "Importar CSV"))
        self.boton5.setText(_translate("cinco", "Importar CSV"))
        self.boton4_2.setText(_translate("cinco", "meanPSDl"))
        self.boton2.setText(_translate("cinco", "Graficar meanPSD y PA CH1"))
        self.boton6_2.setText(_translate("cinco", "meanPSD"))
        self.boton5_2.setText(_translate("cinco", "meanPSD"))
        self.boton3_1.setText(_translate("cinco", "Graficar"))
        self.boton6_4.setText(_translate("cinco", "Regresar"))
