# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'segunda.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_segunda(object):
    def setupUi(self, segunda):
        segunda.setObjectName("segunda")
        segunda.resize(725, 503)
        segunda.setStyleSheet("background-color: rgb(212, 212, 212);")
        self.centralwidget = QtWidgets.QWidget(segunda)
        self.centralwidget.setObjectName("centralwidget")
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setGeometry(QtCore.QRect(370, 50, 3, 90))
        self.line_12.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(390, 250, 70, 3))
        self.line_5.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.boton2_1 = QtWidgets.QPushButton(self.centralwidget)
        self.boton2_1.setGeometry(QtCore.QRect(290, 180, 171, 23))
        self.boton2_1.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.boton2_1.setObjectName("boton2_1")
        self.boton1_3 = QtWidgets.QPushButton(self.centralwidget)
        self.boton1_3.setGeometry(QtCore.QRect(290, 220, 71, 23))
        self.boton1_3.setStyleSheet("background-color: rgb(208, 255, 255);")
        self.boton1_3.setObjectName("boton1_3")
        self.boton3_1 = QtWidgets.QPushButton(self.centralwidget)
        self.boton3_1.setGeometry(QtCore.QRect(390, 80, 71, 23))
        self.boton3_1.setStyleSheet("background-color: rgb(255, 197, 187);")
        self.boton3_1.setObjectName("boton3_1")
        self.boton1 = QtWidgets.QPushButton(self.centralwidget)
        self.boton1.setGeometry(QtCore.QRect(290, 50, 71, 23))
        self.boton1.setStyleSheet("background-color: rgb(151, 191, 255);")
        self.boton1.setObjectName("boton1")
        self.resultado = QtWidgets.QTextEdit(self.centralwidget)
        self.resultado.setGeometry(QtCore.QRect(150, 270, 471, 131))
        self.resultado.setStyleSheet("background-color: rgb(234, 234, 234);")
        self.resultado.setObjectName("resultado")
        self.boton3_2 = QtWidgets.QPushButton(self.centralwidget)
        self.boton3_2.setGeometry(QtCore.QRect(390, 110, 71, 23))
        self.boton3_2.setStyleSheet("background-color: rgb(255, 197, 187);")
        self.boton3_2.setObjectName("boton3_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(390, 20, 21, 20))
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(290, 140, 70, 3))
        self.line.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.boton3_3 = QtWidgets.QPushButton(self.centralwidget)
        self.boton3_3.setGeometry(QtCore.QRect(390, 220, 71, 23))
        self.boton3_3.setStyleSheet("background-color: rgb(255, 197, 187);")
        self.boton3_3.setObjectName("boton3_3")
        self.line_13 = QtWidgets.QFrame(self.centralwidget)
        self.line_13.setGeometry(QtCore.QRect(380, 50, 3, 90))
        self.line_13.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.boton3 = QtWidgets.QPushButton(self.centralwidget)
        self.boton3.setGeometry(QtCore.QRect(390, 50, 71, 23))
        self.boton3.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.boton3.setObjectName("boton3")
        self.boton1_1 = QtWidgets.QPushButton(self.centralwidget)
        self.boton1_1.setGeometry(QtCore.QRect(290, 80, 71, 23))
        self.boton1_1.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.boton1_1.setObjectName("boton1_1")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(390, 140, 70, 3))
        self.line_2.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.boton2 = QtWidgets.QPushButton(self.centralwidget)
        self.boton2.setGeometry(QtCore.QRect(290, 150, 171, 23))
        self.boton2.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.boton2.setObjectName("boton2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 20, 71, 20))
        self.label.setObjectName("label")
        self.boton1_2 = QtWidgets.QPushButton(self.centralwidget)
        self.boton1_2.setGeometry(QtCore.QRect(290, 110, 71, 23))
        self.boton1_2.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.boton1_2.setObjectName("boton1_2")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(290, 250, 70, 3))
        self.line_4.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_19 = QtWidgets.QFrame(self.centralwidget)
        self.line_19.setGeometry(QtCore.QRect(360, 440, 70, 3))
        self.line_19.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.boton6_4 = QtWidgets.QPushButton(self.centralwidget)
        self.boton6_4.setGeometry(QtCore.QRect(360, 410, 71, 23))
        self.boton6_4.setStyleSheet("background-color: rgb(255, 186, 129);")
        self.boton6_4.setObjectName("boton6_4")
        segunda.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(segunda)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 725, 21))
        self.menubar.setObjectName("menubar")
        segunda.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(segunda)
        self.statusbar.setObjectName("statusbar")
        segunda.setStatusBar(self.statusbar)

        self.retranslateUi(segunda)
        QtCore.QMetaObject.connectSlotsByName(segunda)

    def retranslateUi(self, segunda):
        _translate = QtCore.QCoreApplication.translate
        segunda.setWindowTitle(_translate("segunda", "MainWindow"))
        self.boton2_1.setText(_translate("segunda", "Graficar meanPSD y PA CH2"))
        self.boton1_3.setText(_translate("segunda", "Reiniciar CSVs"))
        self.boton3_1.setText(_translate("segunda", "Graficar"))
        self.boton1.setText(_translate("segunda", "Importar CSV"))
        self.boton3_2.setText(_translate("segunda", "meanPSD"))
        self.label_2.setText(_translate("segunda", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">C2</span></p></body></html>"))
        self.boton3_3.setText(_translate("segunda", "Reiniciar CSVs"))
        self.boton3.setText(_translate("segunda", "Importar CSV"))
        self.boton1_1.setText(_translate("segunda", "Graficar "))
        self.boton2.setText(_translate("segunda", "Graficar meanPSD y PA CH1"))
        self.label.setText(_translate("segunda", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Condición 1</span></p></body></html>"))
        self.boton1_2.setText(_translate("segunda", "meanPSD "))
        self.boton6_4.setText(_translate("segunda", "Regresar"))
