# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tres.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tres(object):
    def setupUi(self, tres):
        tres.setObjectName("tres")
        tres.resize(725, 541)
        tres.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.centralwidget = QtWidgets.QWidget(tres)
        self.centralwidget.setObjectName("centralwidget")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(210, 250, 70, 3))
        self.line_4.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 20, 71, 20))
        self.label.setObjectName("label")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(410, 140, 70, 3))
        self.line_3.setStyleSheet("background-color: rgb(36, 255, 12);")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.boton4 = QtWidgets.QPushButton(self.centralwidget)
        self.boton4.setGeometry(QtCore.QRect(410, 50, 71, 23))
        self.boton4.setStyleSheet("background-color: rgb(49, 147, 0);")
        self.boton4.setObjectName("boton4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(310, 250, 70, 3))
        self.line_5.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(410, 250, 70, 3))
        self.line_6.setStyleSheet("background-color: rgb(36, 255, 12);")
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.boton1_1 = QtWidgets.QPushButton(self.centralwidget)
        self.boton1_1.setGeometry(QtCore.QRect(210, 80, 71, 23))
        self.boton1_1.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.boton1_1.setObjectName("boton1_1")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(210, 140, 70, 3))
        self.line.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.boton2_1 = QtWidgets.QPushButton(self.centralwidget)
        self.boton2_1.setGeometry(QtCore.QRect(210, 180, 271, 23))
        self.boton2_1.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.boton2_1.setObjectName("boton2_1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(310, 20, 21, 20))
        self.label_2.setObjectName("label_2")
        self.boton1 = QtWidgets.QPushButton(self.centralwidget)
        self.boton1.setGeometry(QtCore.QRect(210, 50, 71, 23))
        self.boton1.setStyleSheet("background-color: rgb(151, 191, 255);")
        self.boton1.setObjectName("boton1")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(410, 20, 21, 20))
        self.label_3.setObjectName("label_3")
        self.boton4_3 = QtWidgets.QPushButton(self.centralwidget)
        self.boton4_3.setGeometry(QtCore.QRect(410, 220, 71, 23))
        self.boton4_3.setStyleSheet("background-color: rgb(133, 203, 120);")
        self.boton4_3.setObjectName("boton4_3")
        self.boton1_3 = QtWidgets.QPushButton(self.centralwidget)
        self.boton1_3.setGeometry(QtCore.QRect(210, 220, 71, 23))
        self.boton1_3.setStyleSheet("background-color: rgb(208, 255, 255);")
        self.boton1_3.setObjectName("boton1_3")
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setGeometry(QtCore.QRect(290, 50, 3, 90))
        self.line_12.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.boton3_3 = QtWidgets.QPushButton(self.centralwidget)
        self.boton3_3.setGeometry(QtCore.QRect(310, 220, 71, 23))
        self.boton3_3.setStyleSheet("background-color: rgb(255, 197, 187);")
        self.boton3_3.setObjectName("boton3_3")
        self.line_13 = QtWidgets.QFrame(self.centralwidget)
        self.line_13.setGeometry(QtCore.QRect(300, 50, 3, 90))
        self.line_13.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.boton3_2 = QtWidgets.QPushButton(self.centralwidget)
        self.boton3_2.setGeometry(QtCore.QRect(310, 110, 71, 23))
        self.boton3_2.setStyleSheet("background-color: rgb(255, 197, 187);")
        self.boton3_2.setObjectName("boton3_2")
        self.boton1_2 = QtWidgets.QPushButton(self.centralwidget)
        self.boton1_2.setGeometry(QtCore.QRect(210, 110, 71, 23))
        self.boton1_2.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.boton1_2.setObjectName("boton1_2")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(310, 140, 70, 3))
        self.line_2.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_15 = QtWidgets.QFrame(self.centralwidget)
        self.line_15.setGeometry(QtCore.QRect(400, 50, 3, 90))
        self.line_15.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.boton4_1 = QtWidgets.QPushButton(self.centralwidget)
        self.boton4_1.setGeometry(QtCore.QRect(410, 80, 71, 23))
        self.boton4_1.setStyleSheet("background-color: rgb(133, 203, 120);")
        self.boton4_1.setObjectName("boton4_1")
        self.boton3 = QtWidgets.QPushButton(self.centralwidget)
        self.boton3.setGeometry(QtCore.QRect(310, 50, 71, 23))
        self.boton3.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.boton3.setObjectName("boton3")
        self.resultado = QtWidgets.QTextEdit(self.centralwidget)
        self.resultado.setGeometry(QtCore.QRect(120, 260, 471, 131))
        self.resultado.setStyleSheet("background-color: rgb(234, 234, 234);")
        self.resultado.setObjectName("resultado")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(390, 50, 3, 90))
        self.line_8.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.boton4_2 = QtWidgets.QPushButton(self.centralwidget)
        self.boton4_2.setGeometry(QtCore.QRect(410, 110, 71, 23))
        self.boton4_2.setStyleSheet("background-color: rgb(133, 203, 120);")
        self.boton4_2.setObjectName("boton4_2")
        self.boton2 = QtWidgets.QPushButton(self.centralwidget)
        self.boton2.setGeometry(QtCore.QRect(210, 150, 271, 23))
        self.boton2.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.boton2.setObjectName("boton2")
        self.boton3_1 = QtWidgets.QPushButton(self.centralwidget)
        self.boton3_1.setGeometry(QtCore.QRect(310, 80, 71, 23))
        self.boton3_1.setStyleSheet("background-color: rgb(255, 197, 187);")
        self.boton3_1.setObjectName("boton3_1")
        self.line_19 = QtWidgets.QFrame(self.centralwidget)
        self.line_19.setGeometry(QtCore.QRect(330, 440, 70, 3))
        self.line_19.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.boton6_4 = QtWidgets.QPushButton(self.centralwidget)
        self.boton6_4.setGeometry(QtCore.QRect(330, 410, 71, 23))
        self.boton6_4.setStyleSheet("background-color: rgb(255, 186, 129);")
        self.boton6_4.setObjectName("boton6_4")
        tres.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(tres)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 725, 21))
        self.menubar.setObjectName("menubar")
        tres.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(tres)
        self.statusbar.setObjectName("statusbar")
        tres.setStatusBar(self.statusbar)

        self.retranslateUi(tres)
        QtCore.QMetaObject.connectSlotsByName(tres)

    def retranslateUi(self, tres):
        _translate = QtCore.QCoreApplication.translate
        tres.setWindowTitle(_translate("tres", "MainWindow"))
        self.label.setText(_translate("tres", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Condición 1</span></p></body></html>"))
        self.boton4.setText(_translate("tres", "Importar CSV"))
        self.boton1_1.setText(_translate("tres", "Graficar "))
        self.boton2_1.setText(_translate("tres", "Graficar meanPSD y PA CH2"))
        self.label_2.setText(_translate("tres", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">C2</span></p></body></html>"))
        self.boton1.setText(_translate("tres", "Importar CSV"))
        self.label_3.setText(_translate("tres", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">C3</span></p></body></html>"))
        self.boton4_3.setText(_translate("tres", "Reiniciar CSVs"))
        self.boton1_3.setText(_translate("tres", "Reiniciar CSVs"))
        self.boton3_3.setText(_translate("tres", "Reiniciar CSVs"))
        self.boton3_2.setText(_translate("tres", "meanPSD"))
        self.boton1_2.setText(_translate("tres", "meanPSD "))
        self.boton4_1.setText(_translate("tres", "Graficar"))
        self.boton3.setText(_translate("tres", "Importar CSV"))
        self.boton4_2.setText(_translate("tres", "meanPSDl"))
        self.boton2.setText(_translate("tres", "Graficar meanPSD y PA CH1"))
        self.boton3_1.setText(_translate("tres", "Graficar"))
        self.boton6_4.setText(_translate("tres", "Regresar"))
